name: Test ntfy

"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Envoyer notification
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: |
          curl -fsS \
            -H "Title: Test Vinted" \
            -d "Si tu vois ceci, les notifications fonctionnent." \
            "https://ntfy.sh/$NTFY_TOPIC"
